Update patch set 2
Patch Set 2: Code-Review-1

Error: Package: rubygem-public_suffix-3.0.1-1.el7.noarch (temp)
           Requires: ruby >= 2.1
           Available: ruby-2.0.0.648-30.el7.x86_64 (base)
               ruby = 2.0.0.648-30.el7

Patch-set: 2
Reviewer: Gerrit User 80 <80@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=-1